import numpy as np
print("Printing the array of range:")
array=np.arange(1,10,2)
print(array)
print("="*60)
print("Printing the array of random integers:")
array=np.random.randint(1,100,(3,2))
print(array)
print("="*60)
print("Printing the array of random floats:")
array=np.random.rand(3,4)
print(array)
print("="*60)
print("Carrying the operations on the array elements:")
array=np.arange(1,10,2)
print(array+10)
print(array**2)
print(np.sqrt(array))
print("="*60)