import numpy as np
print("Array of Zeros:")
array=np.zeros((2,3))
print(array)
print("="*60)
print("Array of Ones:")
array2=np.ones((2,4))
print(array2)
print("="*60)
print("Identity Matrix:")
array3=np.eye(4)
print(array3)
print("="*60)
print("Filling the matrix with a specific value:")
array4=np.full((3,5),18)
print(array4)